name: Push conda nightly

on: push
  # run every day at 11:15am
  #schedule:
  #  - cron:  '15 11 * * *'
jobs:
  nightly:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python
      - run: conda install -y conda-build
      - name: Checkout TorchServe
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python ts_scripts/install_dependencies.py --environment=dev
      - name: Build torchserve sheel
        run: python binaries/build.py
      - name: Build all packages
        run: python binaries/conda/build_packages.py
      - name: Selectively build packages
        run: python binaries/conda/build_packages.py --ts-wheel=dist/torchserve-*.whl --ma-wheel=model-archiver/dist/torch_model_archiver-*.whl --wa-wheel=workflow-archiver/dist/torch_workflow_archiver-*.whl

