name: Run Regression Tests for CPU nightly binaries

on:
  push:
  # run every day at 6:15am
  #schedule:
  #  - cron:  '15 6 * * *'
  #merge_group:
  workflow_dispatch:

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  regression-cpu-nightly-binaries:
    # creates workflows for OS: ubuntu, macOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.8", "3.9", "3.10"]
        binaries: ["pypi", "conda"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda with Python ${{ matrix.python-version }}
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: python --version
      - run: python a
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev
      - name: Torchserve Regression Tests
        run: |
          python test/regression_tests.py --binaries --${{ matrix.binaries }} --nightly

  #################################
  ### Run when a schedule failed ###
  ##################################
  restart_when_failed:
    name: Restarts the scheduled run when it failed
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && failure()
    needs: [regression-cpu-nightly-binaries]
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
          https://api.github.com/repos/agunapal/serve/workflows/70597408/dispatches \
          -d '{"ref": "${{ github.ref }}" }'
