name: Retry failed workflows
on:
  workflow_run:
    workflows: ["Run Regression Tests for CPU nightly binaries"]
    types:
      - completed

jobs:
  rerun-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.workflow_run.conclusion }}
      - name: Re-run on failure
        if: ${{ github.event.workflow_run.conclusion == 'faliure' }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/rerun-failed-jobs
