name: Push torchserve nightly

on: push
  # run every day at 11:15am
  #schedule:
  #  - cron:  '15 11 * * *'
jobs:
  nightly:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: conda install -y conda-build
      - name: Checkout TorchServe
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install twine
          python ts_scripts/install_dependencies.py --cuda=cu102 --environment=dev
          pip install -e .
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Java Debugging
        run: |
          which javac
      - name: Push torchserve nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        run: ts_scripts/push_nightly.sh torchserve-ag
      - name: Push model-archiver nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        working-directory: model-archiver
        run: ../ts_scripts/push_nightly.sh torch-model-archiver-ag
      - name: Push workflow archiver nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        working-directory: workflow-archiver
        run: ../ts_scripts/push_nightly.sh torch-workflow-archiver-ag
      - name: conda config for auto-upload
        run: conda config --set anaconda_upload yes
      - name: Build conda nighly and push
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_PASSWORD }}
        run: python binaries/build.py --nightly
